/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.5 and the Filter Design Toolbox 4.2.
 *
 * Generated on: 27-Apr-2014 18:30:29
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 127
 * Stable            : Yes
 * Linear Phase      : No
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Specify Precision
 *   Output          : s32,31 -> [-1 1)
 *   Product         : s48,47 -> [-1 1)
 *   Accumulator     : s48,47 -> [-1 1)
 *   Round Mode      : convergent
 *   Overflow Mode   : saturate
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2007b\extern\include\tmwtypes.h 
 */
const int BL = 127;
const int16_T B[127] = {
     -170,   -340,   -507,   -672,   -833,   -988,  -1137,  -1280,  -1414,
    -1540,  -1656,  -1760,  -1852,  -1932,  -1997,  -2048,  -2082,  -2100,
    -2099,  -2080,  -2040,  -1980,  -1897,  -1792,  -1662,  -1508,  -1327,
    -1120,   -884,   -620,   -325,      0,   1040,   2108,   3203,   4320,
     5458,   6612,   7781,   8960,  10148,  11340,  12535,  13728,  14918,
    16100,  17273,  18432,  19576,  20700,  21803,  22880,  23930,  24948,
    25933,  26880,  27788,  28652,  29471,  30240,  30958,  31620,  32225,
    32767,  32225,  31620,  30958,  30240,  29471,  28652,  27788,  26880,
    25933,  24948,  23930,  22880,  21803,  20700,  19576,  18432,  17273,
    16100,  14918,  13728,  12535,  11340,  10148,   8960,   7781,   6612,
     5458,   4320,   3203,   2108,   1040,      0,   -325,   -620,   -884,
    -1120,  -1327,  -1508,  -1662,  -1792,  -1897,  -1980,  -2040,  -2080,
    -2099,  -2100,  -2082,  -2048,  -1997,  -1932,  -1852,  -1760,  -1655,
    -1540,  -1414,  -1280,  -1137,   -988,   -832,   -672,   -507,   -340,
     -170
};
